language: node_js

matrix:
    include:
        - node_js: '10'
        - node_js: '11'
        - node_js: '12'
        - node_js: '13'
        - node_js: '13'
          env:
              - NODE_FLAGS=--harmony-private-methods

    fast_finish: true

script: npm test
